export const tweetsData = [
  {
    handle: `@TrollBot66756542 💎`,
    profilePic: `images/troll.jpg`,
    likes: 27,
    retweets: 10,
    tweetText: `Buy Bitcoin, ETH Make 💰💰💰 low low prices. 
          Guaranteed return on investment. HMU DMs open!!`,
    replies: [],
    isLiked: false,
    isRetweeted: false,
    uuid: "4b161eee-c0f5-4545-9c4b-8562944223ee",
  },
  {
    handle: `@Elon ✅`,
    profilePic: `images/musk.png`,
    likes: 6500,
    retweets: 234,
    tweetText: `I need volunteers for a one-way mission to Mars 🪐. No experience necessary🚀`,
    replies: [
      {
        handle: `@TomCruise ✅`,
        profilePic: `images/tcruise.png`,
        likes: 0,
        retweets: 0,
        tweetText: `Yes! Sign me up! 😎🛩`,
        replies: [],
        isLiked: false,
        isRetweeted: false,
        uuid: `f00c4ce7-9f16-4942-9823-000c05bc99ac`,
      },
      {
        handle: `@ChuckNorris ✅`,
        profilePic: `images/chucknorris.jpeg`,
        likes: 0,
        retweets: 0,
        tweetText: `I went last year😴`,
        replies: [],
        isLiked: false,
        isRetweeted: false,
        uuid: `2cc1b445-7f9e-4d3b-91b2-32e0a5fe5f03`,
      },
    ],
    isLiked: false,
    isRetweeted: false,
    uuid: "3c23454ee-c0f5-9g9g-9c4b-77835tgs2",
  },
  {
    handle: `@NoobCoder12`,
    profilePic: `images/flower.png`,
    likes: 10,
    retweets: 3,
    tweetText: `Are you a coder if you only know HTML?`,
    replies: [
      {
        handle: `@StackOverflower ☣️`,
        profilePic: `images/overflow.png`,
        likes: 0,
        retweets: 0,
        tweetText: `No. Obviosuly not. Go get a job in McDonald's.`,
        replies: [],
        isLiked: false,
        isRetweeted: false,
        uuid: `38d10c5d-20fc-4444-bf0a-533de5b8761f`,
      },
      {
        handle: `@YummyCoder64`,
        profilePic: `images/love.png`,
        likes: 0,
        retweets: 0,
        tweetText: `You are wonderful just as you are! ❤️`,
        replies: [],
        isLiked: false,
        isRetweeted: false,
        uuid: `4a8660cd-714c-4ddb-bd64-1532d45003a6`,
      },
    ],
    isLiked: false,
    isRetweeted: false,
    uuid: "8hy671sff-c0f5-4545-9c4b-1237gyys45",
  },
];
